import Header from '@/components/Header'
import { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

 const Home: NextPage = () => {
  return (
    <>
      <div>
        <Head>
          <title>Apple Store</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/apple.ico" />
        </Head>
        <Header />
      </div>
    </>
  )
}

export default Home
